version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  disable:
    - containedctx
    - cyclop
    - funlen
    - gochecknoglobals 
    - mnd # an analyzer to detect magic numbers # to many reports
    - nestif
    - depguard # (replaced by gomodguard) Go linter that checks if package imports are in a list of acceptable packages
    - exhaustruct # checks if all structure fields are initialized (really useful?)
    - forbidigo # (don't need for a CLI) Forbids identifiers
    - forcetypeassert # (replaced by errcheck) finds missing type assertions
    - godox # detection of FIXME, TODO and other comment keywords
    - loggercheck # Checks key valur pairs for common logger libraries (kitlog,klog,logr,zap
    - paralleltest # (do not want to force this) detects missing usage of t.Parallel() method in your Go test
    - prealloc # (premature optimization) finds slice declarations that could potentially be preallocated
    - promlinter # (no prometheus here) check Prometheus metrics naming via promlint
    - thelper # (useful, but needs some configuration) detects golang test helpers without t.Helper() call and checks the consistency of test helpers
    - wrapcheck # (many detects, really useful?) checks that errors returned from external packages are wrapped
    - wsl # (too strict) forces you to use empty lines

  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    cyclop:
      max-complexity: 33
      package-average: 10
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 100
      statements: 50
    mnd:
      ignored-numbers:
        - "500"
        - "404"
        - "400"
      ignored-functions:
        - os.Chmod
        - os.Mkdir
        - os.MkdirAll
        - os.OpenFile
        - os.WriteFile
        - flag.IntVar
        - time.Sleep
        - time.Duration
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
        path: web/client.go
      - linters:
          - forcetypeassert
          - funlen
          - goconst
          - lll
        path: _test\.go
      - linters:
          - testpackage
        path: parser_test\.go
      - linters:
          - gocognit
        path: parser\.go
      - linters:
          - tagliatelle
        source: image_uris|card_faces
      - linters:
          - reassign
        path: logger\.go
    paths:
      - .github
      - build
      - configs
      - images
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  disable:
    - gofmt
    - gci
  exclusions:
    generated: lax
    paths:
      - .github
      - build
      - configs
      - images
