services:
  # srv:
  #   image: card-service:local
  #   depends_on:
  #     - db
  #   links:
  #     - "db:database"
  #   ports:
  #     - "3000:3000"
  #   volumes:
 #     - ./configs:/config
  img:
    image: nginx:1.27-alpine
    volumes:
      - ./images:/usr/share/nginx/html
    ports:
      - "8080:80"
  db:
    image: postgres:17-alpine3.20
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      APP_DB_USER: tester
      APP_DB_PASS: tester
      APP_DB_NAME: cardmanager
    volumes:
      - ./internal/postgres/testdata/db:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/postgresql
    ports:
      - "15432:5432"
