services:
  srv:
    image: card-service:local
    links:
      - "db:database"
    ports:
      - "3000:3000"
    volumes:
      - ./configs:/config
  img:
    image: nginx:1.23
    volumes:
      - ./images_2:/usr/share/nginx/html
    ports:
      - "8080:80"
  db:
    image: postgres:16-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      APP_DB_USER: tester
      APP_DB_PASS: tester
      APP_DB_NAME: cardmanager
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
