logging:
  level: INFO

database:
  host: 127.0.0.1
  port: 15432
  database: cardmanager
  username: tester
  password: tester

mtgjson:
  datasetUrl: https://mtgjson.com/api/v5/AllPrintings.json.zip
  client:
    timeout: 60s

scryfall:
  baseUrl: https://api.scryfall.com
  client:
    timeout: 60s
    retries: 3
    retryDelay: 5s
    retrieables:
      - 502
      - 520
    delay: 50ms

storage:
  location: /tmp/images
  mode: REPLACE
