logging:
  level: INFO

database:
  host: 127.0.0.1
  port: 15432
  database: cardmanager
  username: tester
  password: tester

http:
  timeout: 60s

mtgjson:
  downloadURL: https://mtgjson.com/api/v5/AllPrintings.json.zip

scryfall:
  downloadURL: https://api.scryfall.com/cards/{code}/{number}/{lang}?format={format}&version=normal

storage:
  location: /tmp/images
  mode: REPLACE
